apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: wind-kafka-demo
spec:
  location: ApplicationMenu
  text: Wind Kafka Demo
  applicationMenu:
    section: Demos
    text: Wind Kafka Demo
  href: https://wind-kafka-frontend-wind-kafka.apps.cluster-4tqtj.4tqtj.sandbox481.opentlc.com
---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: wind-kafka-console
spec:
  location: ApplicationMenu
  text: Wind Kafka Kafka Console
  applicationMenu:
    section: Demos
    text: Wind Kafka (Kafka Console)
  href: https://wind-kafka-console-wind-kafka.apps.cluster-4tqtj.4tqtj.sandbox481.opentlc.com

