FROM registry.access.redhat.com/ubi9/openjdk-17:latest AS build

USER 0
RUN microdnf install -y maven && microdnf clean all

WORKDIR /workspace
COPY legacy/pom.xml legacy/pom.xml
COPY legacy/apps/visualizer/pom.xml legacy/apps/visualizer/pom.xml
COPY legacy/apps/visualizer/src legacy/apps/visualizer/src

RUN mvn -f legacy/pom.xml -pl apps/visualizer -am package -DskipTests

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY --from=build /workspace/legacy/apps/visualizer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8082
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

