FROM registry.access.redhat.com/ubi9/openjdk-17:latest AS build

USER 0
WORKDIR /workspace
COPY modern modern
RUN chown -R 1001:0 /workspace
USER 1001

# Build JVM (fast-jar) using the Maven Wrapper.
RUN ./modern/mvnw -f modern/pom.xml -pl apps/kaoto-consumer -am package -DskipTests

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY --from=build /workspace/modern/apps/kaoto-consumer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8083
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

