FROM registry.access.redhat.com/ubi9/openjdk-17:latest AS build

USER 0
RUN microdnf install -y maven && microdnf clean all

WORKDIR /workspace
COPY modern modern

RUN mvn -f modern/pom.xml -pl apps/event-consumer -am package -DskipTests

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY --from=build /workspace/modern/apps/event-consumer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8081
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

