FROM registry.access.redhat.com/ubi9/openjdk-17:latest AS build

USER 0
RUN microdnf install -y maven && microdnf clean all

WORKDIR /workspace
COPY modern/pom.xml modern/pom.xml
COPY modern/apps/visualizer/pom.xml modern/apps/visualizer/pom.xml
COPY modern/apps/visualizer/src modern/apps/visualizer/src

RUN mvn -f modern/pom.xml -pl apps/visualizer -am package -DskipTests

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY --from=build /workspace/modern/apps/visualizer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8082
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

