FROM registry.access.redhat.com/ubi9/openjdk-17:latest AS build

WORKDIR /workspace
COPY modern modern

RUN ./modern/mvnw -f modern/pom.xml -pl apps/visualizer -am package -DskipTests

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY --from=build /workspace/modern/apps/visualizer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8082
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

