quarkus.http.port=8081

quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*

demo.broker.url=${DEMO_BROKER_URL:tcp://localhost:61616}
demo.broker.username=${DEMO_BROKER_USERNAME:admin}
demo.broker.password=${DEMO_BROKER_PASSWORD:admin}
demo.broker.queue=${DEMO_BROKER_QUEUE:demo.events}

# Used in log lines to differentiate consumers in Loki.
demo.consumer.name=${DEMO_CONSUMER_NAME:event-consumer}

camel.component.jms.connection-factory=#connectionFactory

