apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: loki-bucket-odf
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  generateBucketName: loki-bucket-odf
  storageClassName: openshift-storage.noobaa.io

