FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY legacy/apps/event-consumer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8081
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

