apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - odf/objectbucketclaim.yaml
  - odf/secret-sync-rbac.yaml
  - odf/secret-sync-job.yaml
  - lokistack.yaml
  - collector-rbac.yaml
  - clusterlogging.yaml

