apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - amq-broker/subscription.yaml
  - logging/loki-subscription.yaml
  - logging/cluster-logging-subscription.yaml
  - devspaces/subscription.yaml
  - odf/subscription.yaml

