apiVersion: v1
kind: Namespace
metadata:
  name: demo-camel-mta
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-logging
  labels:
    openshift.io/cluster-monitoring: "true"
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-operators-redhat
---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-devspaces

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-storage

---
apiVersion: v1
kind: Namespace
metadata:
  name: openshift-mta

