apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: modern-event-consumer
spec:
  runPolicy: Serial
  source:
    type: Git
    git:
      uri: https://github.com/panchoraposo/demo-camel-mta.git
      ref: main
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: modern/apps/event-consumer/Containerfile
  output:
    to:
      kind: ImageStreamTag
      name: modern-event-consumer:latest
  triggers:
    - type: ConfigChange
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: modern-event-consumer
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"modern-event-consumer:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"app\")].image"}]'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: modern-event-consumer
  template:
    metadata:
      labels:
        app: modern-event-consumer
    spec:
      containers:
        - name: app
          image: ' '
          imagePullPolicy: Always
          env:
            - name: DEMO_BROKER_URL
              value: tcp://amq-broker-hdls-svc:61616
            - name: DEMO_BROKER_USERNAME
              value: admin
            - name: DEMO_BROKER_PASSWORD
              value: admin
            - name: DEMO_BROKER_QUEUE
              value: demo.events
            - name: DEMO_CONSUMER_NAME
              value: event-consumer
          ports:
            - containerPort: 8081
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: modern-event-consumer
spec:
  selector:
    app: modern-event-consumer
  ports:
    - name: http
      port: 8081
      targetPort: http

