apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-camel-mta

resources:
  - imagestreams.yaml
  - producer.yaml
  - consumer.yaml
  - kaoto-consumer.yaml
  - visualizer.yaml

