apiVersion: v1
kind: ServiceAccount
metadata:
  name: wind-kafka-pipeline
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wind-kafka-pipeline
rules:
  - apiGroups: ["build.openshift.io"]
    resources: ["buildconfigs", "buildconfigs/instantiate", "builds"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wind-kafka-pipeline
subjects:
  - kind: ServiceAccount
    name: wind-kafka-pipeline
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wind-kafka-pipeline

