apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: oc
spec:
  params:
    - name: script
      type: string
  steps:
    - name: oc
      image: registry.redhat.io/openshift4/ose-cli:latest
      script: |
        #!/usr/bin/env bash
        set -euo pipefail
        $(params.script)

