FROM registry.access.redhat.com/ubi9/openjdk-17:latest AS build

WORKDIR /workspace
COPY legacy legacy

RUN sh legacy/mvnw -f legacy/pom.xml -pl apps/queue-producer -am package -DskipTests

FROM registry.access.redhat.com/ubi9/openjdk-17-runtime:latest
WORKDIR /deployments
COPY --from=build /workspace/legacy/apps/queue-producer/target/quarkus-app/ /deployments/quarkus-app/

EXPOSE 8080
USER 185
ENTRYPOINT ["java","-jar","/deployments/quarkus-app/quarkus-run.jar"]

